name: go-lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  golangci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: run lint
        run: make go-lint
